import Head from "next/head";

import NavBar from "./NavBar";
import Footer from "./Footer";

interface childrenProps {
  children: JSX.Element;
}

export default function Layout({ children } : childrenProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      {children}
      <Footer />
    </>
  );
}
